name: Rust

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --all-features
    - name: Run tests
      run: cargo test --release --all-features
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Run benchmarks
      run: cargo bench
